export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// export const REGISTER_USER_INITIATE = "REGISTER_USER_INITIATE";
// export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// export const LOGIN_USER_INITIATE = "LOGIN_USER_INITIATE";
// export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
// export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const AUTHENTICATE_USER_INITIATE = "AUTHENTICATE_USER_INITIATE";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USER_ERROR";
