export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const AUTHENTICATE_USER_INITIATE = "AUTHENTICATE_USER_INITIATE";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_CURRENT_USER";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const UPDATE_USER_INITIATE = "UPDATE_USER_INITIATE";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_INITIATE = "CREATE_JOB_INITIATE";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_INITIATE = "GET_JOBS_INITIATE";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
